export interface Aluno {
  id: number;
  nome: string;
  telefone: string;
  aludias: string;
  localid: number,
  local: string,
  servicoid: number,
  servico: string,
  email?: string;
  datanasc?: string;
  datainicio?: string;
  cpf?: string;
  ativo: boolean;
  diasAula: [];
  planoid: number;
  plano: string;
  frequenciaid: number;
  frequencia: string;
  mostrarEquipto: boolean;
  aludia0: boolean;
  aludia1: boolean;
  aludia2: boolean;
  aludia3: boolean;
  aludia4: boolean;
  aludia5: boolean;
  aludia6: boolean;
  aluhora0: string;
  aluhora1: string;
  aluhora2: string;
  aluhora3: string;
  aluhora4: string;
  aluhora5: string;
  aluhora6: string;
}